### PR TITLE
updating plugin audiophile_audition 1.0.0

### PR DESCRIPTION
**Pull request by pattdepanick**
Please merge this new plugin for greek network stream https://stream.psychomed.gr/index.html

### CODE REVIEW

**Comment by volumio** [comment]
Great! Would you please upload the source code to the repo? This way we can deploy it for all supported platforms 

Thanks

**Comment by pattdepanick** [comment]
ping ?

**Comment by pattdepanick** [comment]
Are we done ?

**Comment by volumio** [comment]
Hi, we need the sources on the master branch. Can you do a PR please?

**Comment by balbuze** [comment]
no sources...

**Pull request closed without merging**
