### PR TITLE
new plugin, pirateaudio

### PR DESCRIPTION
**Pull request by Ax-LED**
Dear Volumio-Team,
i am not sure if i did the pull request the right way. Please check my new plugin miscellanea/pirateaudio.

Regards

AxLED

### CODE REVIEW

**Comment by balbuze** [comment]
Please just source code. No zip, no node modules, no plugin.json. we take care of this. Thanks.

**Comment by Ax-LED** [comment]
@balbuze 

now i uploaded the requested files to the gh-pages branch of my repo and clicked pull request again.
Path: volumio-plugins/plugins/volumio/armhf/miscellanea/pirateaudio/
I also deleted the pirateaudio.zip in the repo, as you told me.
Is it the right way now?

With the upload earlier this day i followed the volumio documentation which says to to a "volumio plugin publish" command.

Looking forward hearing from you.

Regards

AxLED

**Comment by balbuze** [comment]
Hello. Your Pr must be only for master branch. The zip is automatically generated in gh-pages

**Comment by Ax-LED** [comment]
I dont understand your answer. Is there something i have to do now? If yes, can you please give me some instructions? 
AxLED

**Comment by balbuze** [comment]
We need just your code in master branch. Nothing in gh-pages. As I said, the zip is generated automatically from the source when validated. So your code must be in miscellanea/pirateaudio (or the name you want) as other plugins. Have a look.

**Comment by Ax-LED** [comment]
wrong PR, merged with #524

**Pull request closed without merging**
