### PR TITLE
Adding search to Spotify plugin

### PR DESCRIPTION
**Pull request by skikirkwood**
Added search to Spotify plugin.  Spotify returns the following in a search request - artists, albums, playlists, tracks.  Modified the explodUri method so you can use "Play" from the hamburger menu to add albums, playlists and tracks to the queue as well as "play" them.

When you click on a Spotify artist, we show the top tracks from the artist, their albums, and related artists. The latter is really cool!

When I'm done with this I'll refactor the code to make it simpler as there is some duplication right now in search, explodeUri and the core support functions.

Known issues:

1. There is an empty hamburger menu item for artists - I could use guidance on how to fix this.  When it is fixed I can them implement a Play and Add to Queue functionality for artists, which will add their top tracks and albums.
2. The previous checkin added Spotify Categories & Moods, and these should not have a hamburger menu.
3. Occasionally you get a 502 bad gateway response from Spotify - no idea why.

To Do:

1. Incorporate Spotify album art when Volumio supports URL's in addition to current method.
2. Add paging behavior when Volumio supports the notion of paging.
3. Refactor code to eliminate duplicate code and add better error checking.

Finally, not sure what I did here where this can't be automatically merged, let me know if I did anything wrong in the fork and pull request.

### CODE REVIEW

**Comment by volumio** [comment]
I'm having some difficulties in merging ...
What I get is 
remote: Permission to skikirkwood/volumio-plugins.git denied to volumio.
fatal: unable to access 'https://github.com/skikirkwood/volumio-plugins.git/': The requested URL returned error: 403

Really no clue here... 

Going with a manual approach... Hopefully I'll get it right..

**Comment by volumio** [comment]
Merged... But don't know if everything is allright... Search works no more...
I'm trying on this...
http://updates.volumio.org/pi/volumio/0.963/volumio-0.963-2016-07-25-pi.img.zip

**Comment by skikirkwood** [comment]
Strange.  Just downloaded the new image, let me put it on my Pi and see what's up.

**Comment by volumio** [comment]
Ok, I'll be right here...

**Comment by skikirkwood** [comment]
Just installed the new image.  Search is indeed busted.  Firing up the debugger!

**Comment by skikirkwood** [comment]
Ok, something went wrong with the merge.  The image you sent me has the old version of the Spotify index.js file - the one with my browse additions but none of the new stuff for search.  Let me apply the new index.js to it, make sure it works, and then I'll get you the new version of the file to merge in.

**Comment by volumio** [comment]
Yes I didn't upload the new plugin yet...

**Comment by skikirkwood** [comment]
Ah, got it.  I copied over the new Spotify index.js and am now running under the debugger.  Everything else seems to work, but search is still broken.  It looks like the search function is actually not even being called, so no idea what’s up - still at it.  

I guess I can disable the plugin and see if search is working for Webradio as before, then take it from there.

**Comment by skikirkwood** [comment]
Ok, I disabled the Spotify plugin - the UI for disabling generated this:

info: Stopping plugin spop
Missing error handler on `socket`.
TypeError: Cannot read property 'then' of undefined
    at PluginManager.stopPlugin (/volumio/app/pluginmanager.js:253:13)
    at PluginManager.disableAndStopPlugin (/volumio/app/pluginmanager.js:1196:7)
    at CoreCommandRouter.disableAndStopPlugin (/volumio/app/index.js:682:28)
    at Socket.<anonymous> (/volumio/app/plugins/user_interface/websocket/index.js:1367:44)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at Socket.onevent (/volumio/node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/volumio/node_modules/socket.io/lib/socket.js:295:12)
    at Client.ondecoded (/volumio/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/volumio/node_modules/component-emitter/index.js:134:20)



So I just renamed the spop folder and started Volumio up again.  Now with no Spotify plugin I typed “chill” in the search bar and got back nothing.  Webradio typically gives back pages of radio stations.  So it appears the mechanism that calls the plugin controllers for search is busted.

I’ll fire up the debugger on the Volumio core and see if I can spot something.

**Comment by skikirkwood** [comment]
Fired up the debugger and stepped through CoreMusicLibrary.prototype.search
in musiclibrary.js. I can see it calling the search function in webradio/index.js and webradio finds 498 results for “chill”, but they are never rendered in the UI.  Again, this is without the Spotify plugin being active.

So something in this new image broke the search mechanism, I’m not sure I can debug it further since I haven’t stepped through the rest of the Volumio core yet.

**Comment by skikirkwood** [comment]
Final thought here is it looks like the music library controller is doing the right thing and returning the correct results, so I’m guessing some change in the UI is breaking the rendering of the results.

**Comment by volumio** [comment]
MMMM I see 
Tomorrow I will investigate it better, with the socket controller on hand

**Comment by volumio** [comment]
thanks for the great work so far BTW!

**Comment by skikirkwood** [comment]
When Spotify search works it kicks ass!  I see your changes in the volumio-ui repo to use URL’s of images, so I’ll look at that more and get something ready to switch over to them  High quality artwork is a huge part of a positive user experience.

**Comment by volumio** [comment]
With the UI fixed, it works just brilliant!!! Awesome!!! Agree that we should limit the webradios results, they're very intrusive...

**Comment by skikirkwood** [comment]
Cool!  Until we have pagination I think it would be a good idea for music services to return a max of 20 items per category and then we can add “Show more” links with the pagination URL’s later.  And in the future letting users reorder the priority of music service results would be good.  A quick fix for now would be to add “limit=20” to the query parameters of the Shoutcast API call on line 664 of webradio/index.js.

Do you have a link to a newer image I can try?  I hooked up albumart items with URL’s from Spotify, but whenever I do and comment out the icon of the item I never get to the next screen in the current image.  No error message, perhaps your UI fix will fix this as well.

After the Spotify artwork is working I’d like to make sure the UI features such as adding to favorites works, as well as hitting “Play” from the hamburger menu for artists.  After that it would be cool to have additional UI options such as creating a queue/playlist of items using a Spotify track/album/artist as a seed, which the new API supports.  We could do this with non-Spotify items as well.

https://developer.spotify.com/web-api/get-recommendations/ <https://developer.spotify.com/web-api/get-recommendations/>

Eventually, it would be nice to have the Spotify UI look like a simplified version of the Spotify Web player.  But under Volumio it will be more powerful as it works seamlessly with one’s own music library and other music service plugins.

**Comment by volumio** [comment]
I checked now and it seems we got a regression... in browse it does not work, but it does on main playback page and in the queue... I think we could start with those now.. 

I'll be away for 2 weeks... So think to implement this we need to wait a while...

Here you have the image:
http://updates.volumio.org/pi/volumio/0.973/volumio-0.973-2016-07-27-pi.img.zip

**Comment by skikirkwood** [comment]
Ok, I’ll start with those two.

**Comment by volumio** [comment]
New image with images also on browse:
http://updates.volumio.org/pi/volumio/0.975/volumio-0.975-2016-07-27-pi.img.zip

enjoy!!!

**Comment by skikirkwood** [comment]
Got the Spotify album artwork integrated and it looks awesome, especially on my iMac’s big screen!  Should have a pull request ready later tonight!

**Comment by volumio** [comment]
Great!!! really looking forward!

**Comment by skikirkwood** [comment]
Got just about it all working and it’s really cool but I’ve been fighting a bug since day one, and it keeps showing up here.  After playing tracks and deleting them from the queue, I get into a strange state where I can no longer play tracks and get a message about an error exploding a URI with a property ‘service’ of undefined.  Here’s an example log of the situation:

info: [1469686115534] ------------------------------ 64ms
info: CoreCommandRouter::volumioAddQueueItems
info: [1469686119190] CoreStateMachine::addQueueItems
info: [1469686119195] CorePlayQueue::addQueueItems
info:  uri=spotify:track:42SYMWISn7xUpTNPLw9V5E, title=Oh Yeah - Remastered, service=spop
info: First index is 0
info: ADDING THIS ITEM TO QUEUE: {"uri":"spotify:track:42SYMWISn7xUpTNPLw9V5E","title":"Oh Yeah - Remastered","service":"spop"}
info: Exploding uri spotify:track:42SYMWISn7xUpTNPLw9V5E in service spop
info: [1469686119818] CorePlayQueue::saveQueue
info: Adding item to queue: [{"uri":"spotify:track:42SYMWISn7xUpTNPLw9V5E","service":"spop","name":"Oh Yeah - Remastered","artist":"Yello","album":"Stella","type":"track","duration":185,"tracknumber":3,"albumart":"https://i.scdn.co/image/829abfb9ad0cff4e3287daa983383954fa7baac9","samplerate":"320Kbps","bitdepth":"16 bit","trackType":"spotify"}]
info: CoreCommandRouter::volumioPushQueue
info: [1469686119836] InterfaceWebUI::pushQueue
info: [{"uri":"spotify:track:42SYMWISn7xUpTNPLw9V5E","service":"spop","name":"Oh Yeah - Remastered","artist":"Yello","album":"Stella","type":"track","duration":185,"tracknumber":3,"albumart":"https://i.scdn.co/image/829abfb9ad0cff4e3287daa983383954fa7baac9","samplerate":"320Kbps","bitdepth":"16 bit","trackType":"spotify"}]
info: [1469686119853] CoreStateMachine::updateTrackBlock
info: [1469686119861] CorePlayQueue::getTrackBlock
info: An error occurred while exploding URI: TypeError: Cannot read property 'service' of undefined

**Comment by skikirkwood** [comment]
Ok, just fired up the Webstorm debugger and I can see where this is happening.  On line 45 of playqueue.js there is a reference to this.arrayQueue[nStartIndex] where nStartIndex is 63, but this.arrayQueue is of length 1.  Some sequence to update the queue fails to resize the array and this causes all of kinds of problems.

As a quick workaround I guess I can check for the length here, and change the index to the largest value of the actual current queue length to avoid this problem.

**Comment by volumio** [comment]
yes that could be a solution

**Comment by volumio** [comment]
You made it, works perfect. Building the latest releases with this fix!

**Comment by skikirkwood** [comment]
Thanks for getting both changes in.  Awesome that Spotify provides artwork for basically everything other than artist combos.  For now I'm using the 640x640 image which looks great as the 400x400 image on the Playback page.  Nice to see images of artists, playlists and genres too!  Their CDN makes it fast to get the images too.

Need to get "Play" working for artists then I'll refactor the code and clean it up with better error checking.

**Pull request merged**
