### PR TITLE
Merge Nanosound CD and NanoSound updates

### PR DESCRIPTION
**Pull request by nanomesher**
Changes to NanoSound plugin v.1.6.1
- New better display layout
- Multilanguage settings

Add New Nanosound CD plugin
- First Check in
- Multilanguage settings screen

### CODE REVIEW

**Comment by balbuze** [comment]
please can you tell which arch/hardware (arm/x86) is supported. TY

**Comment by balbuze** [comment]
Installation is fine, but the plugin fails to start `Mar 28 17:35:31 volumio-rpi2 volumio[919]: info: Loading plugin "nanosound_cd"...
Mar 28 17:35:33 volumio-rpi2 volumio[919]: error: !!!! WARNING !!!!
Mar 28 17:35:33 volumio-rpi2 volumio[919]: error: The plugin music_service/nanosound_cd failed to load, setting it to stopped. Error: Error: Cannot find module 'sleep'
Mar 28 17:35:33 volumio-rpi2 volumio[919]: error: Stack trace: Error: Cannot find module 'sleep'
`

**Comment by nanomesher** [comment]
We cannot reproduce this.  Which platform was used to try?

Doubled checked package.json and "sleep": "^5.1.1" is there.

https://github.com/nanomesher/volumio-plugins/blob/master/plugins/music_service/nanosound_cd/package.json

While running ` volumio plugin install`, did it create below folder?
node_modules\sleep

**Comment by balbuze** [comment]
Everything seems fine with a fresh install of volumio...
Now your plugin is online!

**Comment by nanomesher** [comment]
Thanks a lot!  
How about nanosound plugin?  There is an update too.  Thanks

**Comment by balbuze** [comment]
Can you please send a PR just for nanosound plugin? TY

**Comment by nanomesher** [comment]
Added  https://github.com/volumio/volumio-plugins/pull/323

thanks

**Pull request merged**
