### PR TITLE
Major update for LastFM

### PR DESCRIPTION
**Pull request by Saiyato**
- Added similar artists/tracks lookup in the browse menu (icon can be changed to match Volumio style, but I'm not good at this)
- The results now perform a search against the library if clicked
- Some cleanup in the logic and better logic for extracting info from streaming services
- Dynamic support for music services (users can maintain them in settings)

Second try, without package.json

### CODE REVIEW

**Comment by Saiyato** [comment]
@balbuze tried closing the previous one and without package.json I'm still getting the same conflict :(

**Comment by volumio** [comment]
@Saiyato merged. Few comments:
- Please don't use SVG as icon, better PNG (it's compatible with most frontends)
- Why giving the chance to select the services and not use them all by default?
- Why asking people to generate an API key? What about integrating one by default? We want 
plugins to be as user friedly as possible.
Thanks for this great plugin!

@balbuze could you publish please for X86?

**Comment by balbuze** [comment]
done!

**Comment by Saiyato** [comment]
Hi @volumio,

- I will update the SVG for a PNG one, thought the higher the quality, the better.

- The selection of services allows for true forward compatibility, there a difference between 'song-services' and 'streaming-services' in terms of detection and timer settings.

- I'm not sure about registering an API key and putting it in the sources, I can request one, but that would be registered to me (personally). If you want I can ask for a Volumio one, but putting it in open source software allows for other people to (mis)use it. What's the best step forward? 

Cheers

**Pull request merged**
