### PR TITLE
update ytdl-core version

### PR DESCRIPTION
**Pull request by aerickson**
Specify the latest version of ytdl-core. 

Fixes https://github.com/volumio/volumio-plugins/issues/335.

https://www.npmjs.com/package/ytdl-core

### CODE REVIEW

**Comment by aerickson** [comment]
https://github.com/volumio/volumio-plugins/pull/334 also updates ytdl-core.

**Comment by aerickson** [comment]
0.29.5 is out now.

**Comment by aerickson** [comment]
@balbuze Sorry to at mention you, but will you please take a look at this PR and/or #334? Thanks :)

**Comment by balbuze** [comment]
which PR is ok ? both ?

**Comment by aerickson** [comment]
#334 is a sort of large refactoring and an upgrade of ytdl-core (an older version). This change upgraded ytdl-core to the latest version. Landing #334 and then this PR would have worked. Landing just this change should fix the youtube plugin.

If you're interested in merging/reviewing #334 I can rebase it.

Aside: When/how do plugins get updated?

Thanks :)

**Comment by aerickson** [comment]
> Aside: When/how do plugins get updated?

Ah, I found the update button in the 'search plugins' section.

**Comment by balbuze** [comment]
:+1: 
I tested on my rpi4 and virtual x86. Works fine!

**Comment by volumio** [comment]
@balbuze can you update the plugin? thanks!

**Comment by balbuze** [comment]
Humm.. I updated it on August 22 version 0.1.0 form arm and x86. Something I missed?

**Comment by volumio** [comment]
Sorry, it's me the one who missed something here ;)

**Pull request merged**
