### PR TITLE
Remove `node_modules` dir from all plugins

### PR DESCRIPTION
**Pull request by ashthespy**

### CODE REVIEW

**Comment by a-i-ks** [comment]
I welcome this pull request. Is **npm install** called automatically when installing plugins or must each plugin call it in the install.sh? If the latter is the case, **npm_install**  should be added to each install.sh where the node_modules dir has been removed.

**Comment by ashthespy** [comment]
@a-i-ks `node_modules` are packaged into the `plugin.zip` that is hosted on `gh_pages` branch of this repo. This is to avoid having to build external modules/bindings on poor pi's..

**Comment by a-i-ks** [comment]
@ashthespy Thanks for the explanation.  So if I understood that correctly, the best way is to add the `node_modules `folder to the` .gitignore`. And don't run the `npm install` in `install.sh`. Instead use the `volumio plugin publish` command as soon as the plugin is finished developed?

**Comment by ashthespy** [comment]
Yeah, this is my [.gitignore](https://github.com/ashthespy/volumio-plugins/blob/05ed6edb39237f2f48ea09e4467175aaa9117316/.gitignore#L1-L2), should probably add it to this PR as well. 

```.gitignore
# Ignore all node_modules in all sub dirs
node_modules/
```

When you package your plugin, just include your `node_modules` folder, that contains all the right modules for your architecture. This should be PR against the `gh_pages` branch, while this branch aims to keep the code checked in. I wrote some scripts to automate this via a CI, but its a pain to work with this repo in its current state. 

[`volumio plugin publish`](https://github.com/volumio/Volumio2/blob/0e846201a5a7f222da3ed4356fdcbb7742fefc1c/pluginhelper.js#L394) does this by running `npm install` if it doesn't find a `node_modules` folder.

**Comment by volumio** [comment]
I believe to make this effective we should "rebase" the repo, to clean all the node_modules history as well. Do you have any idea on that?

**Comment by ashthespy** [comment]
Not sure if rebasing will help - to reduce the size of the repo, you'd have to re-write the history of the repo by deleting all instances of `node_modules` from history using `--index-filter` for example. 

Maybe its an option to finally split out each plugin into its own repo `plugin-*` - like how the current `platform-*` repos are handled? I should have some scripts that does this, keeping the commit history,  like in [Volumio-SpotifyConnect](https://github.com/ashthespy/Volumio-SpotifyConnect)

**Comment by volumio** [comment]
as of now I've not foun an easy solution.. Ash could you help on that? We want to remove ideally all histories of committed node_modules.
+1 for the idea of separate repos for sources. We are studying a new iteration of plugin manager and repo, I will contact you for your opinion if you like ;)

**Comment by ashthespy** [comment]
Removing `node_modules` from history will rewrite all commits from the point, so it will break all the current forks. Not sure if we should do that now. 
Would rather wait for this new iteration of plugin manager, I am eager for it, as IMO the current ecosystem is becoming hard to work with! We could still have a central "collection" repo that becomes the official distribution source, while checking in the code into separate repos, this should greatly help with proper versioning and tracking of changes. Either way, I'd be happy to help, let me know!

>
>One action we could do, is to push gh-pages without history. Do you have an idea on how to achieve that?

Currently all the `git clone` operations in the plugin helper use shallow clone - https://github.com/volumio/Volumio2/pull/1515
So culling the history of the `gh-pages` branch doesn't bring in much savings. We could invistigate the savings by just setting `--depth 1`  instead of the `--depth 5`?

**Comment by volumio** [comment]
OK, ash. I will contact you for the new plugin manager ;)

**Pull request merged**
