### PR TITLE
Enable circular references while scanning for binary

### PR DESCRIPTION
**Pull request by WebReflection**
In order to avoid issues with circular references,
this PR would like to avoid recursive scans so that
it is possible to send data via CircularJSON,
as mentioned in the following PR:

https://github.com/socketio/socket.io-parser/pull/80

### CODE REVIEW

**Comment by volumio** [comment]
Can't accept as it's a node module file...

**Comment by WebReflection** [comment]
you haven't even read the PR that has nothing to do with a node module, isn't it?

**Comment by volumio** [comment]
I've read it, and it surprised me to see that the only file changed was this:
plugins/miscellanea/rfampswitch/node_modules/has-binary2/index.js

or am I missing something?

**Comment by WebReflection** [comment]
ah so you meant I've changed a node_module ... ok, sorry, I thought you meant ciruclar-json ...

then I guess the last hope is in here: https://github.com/darrachequesne/has-binary/pull/3

**Comment by volumio** [comment]
Yes, ideally we need to wait for the PR being merged on the node repo itself.

Only thing we can do to avoid the issue (BTW, what is this meant to solve in real usage scenario?), we can refactor the code in the plugin itself in order to circumvent this.
BTW, Ciao Andrea piacere di rileggerti!

**Pull request closed without merging**
