### PR TITLE
Add TuneIn radio initial support

### PR DESCRIPTION
**Pull request by piffio**
This plugins adds support to TuneIn Radio streams and Podcasts.

This is my first Volumio plugin, therefore feedback is more than welcome.
The initial release is meant at providing a basic working functionality and to get early testing. I have been testing thoroughly both radio stations and podcasts, but I expect some users will get into special corner cases.

The plugin caches results from TuneIn, to avoid being blacklisted.
Ideally we should get a dedicated partnerId from TuneIn, which would increase the request quota as well as enable support for authentication and other additional features, but so far I have got no replies to my emails :(

What is supported:
* Browsing and playing Radio Stations
* Browsing and playing Podcasts (Shows)
* Searching for content

What is not supported (yet?):
* Login to your personal account, and all the features that depend on this capability (namely the ability to access your favorite TuneIn streams from Volumio)

### CODE REVIEW

**Comment by piffio** [comment]
@volumio is there anything else I need to do in order to get this PR reviewed?
Just let me know in case anything is missing

**Comment by volumio** [comment]
Hi Sergio,
actually I think your work is awesome! 
I was also thinking, why not integrate it directly into Volumio itself, rather than a plugin? Would you be open to that?

**Comment by piffio** [comment]
Honestly, I though about it halfway through the implementation when I noticed the similarities with the embedded `webradio` code, but I still felt the right way to submit a new standalone feature would be through a plugin.

What I would suggest is a 2 steps approach:
* Unless you see any blocker, I'd suggest moving on an publishing the plugin. This will deliver the feature to all those users who have been waiting for it, and will provide some early testing and possibly bug reports to cover for some non trivial corner cases
* While the plugin matures I can work on a structured PR for the Volumio repo to eventually replace it.

Would that work?

In that case I'll open an issue soon on the Volumio repo to discuss some details about the implementation. Namely, I am unsure about how much to integrate TuneIn within the webradio section.

**Comment by volumio** [comment]
Hi Sergio,
that's a good plan, let's go with this 2 steps approach. I'll review and merge asap

**Comment by volumio** [comment]
@piffio Plugin published, very well done! 
I've made few cosmetics tweaks:
- Icon is now same size as the others
- Configured proper category  ( so the 3 dots are not showed on categories)
- Added icons to top level 

That's definetely a great start, looking forward to see your improvements !
Ciao a presto!

**Pull request merged**
