### PR TITLE
Update rotary encoder

### PR DESCRIPTION
**Pull request by Saiyato**
All patches from previous fork/PR included

Created a branch for this plugin, maybe that way I can create PR's per plugin.

### CODE REVIEW

**Comment by volumio** [comment]
Perfect! Will test & publish asap

**Comment by Ghembs** [comment]
I'm sorry: I mistakenly merged before a proper testing, since there were some errors I'm going to revert the PR.

**Comment by Saiyato** [comment]
This PR does appear to be merged, should I create a new one? Or how does this work? :)
Also, what errors did you encounter? I might be able to fix them in the near future.

**Comment by dmnc-net** [comment]
Hi folks, anything new? @Ghembs what errors did you encounter?

**Pull request merged**
