### PR TITLE
Add Tradfri Plugin

### PR DESCRIPTION
**Pull request by reshnm**
I have create a plugin for my own purposes but I thought it might be helpful for others too.
The plugin lets you connect to a local IKEA Tradfri Gateway and switch Tradfri devices on/off based on the Volumio player state.
When Volumio is playing music the configured Tradfri device or group is switched on. When the playback is paused or stopped the device or group is switched off after a configurable timeout.

I use it to switch on/off my active speakers which are connected to an IKEA smart outlet.

### CODE REVIEW

**Comment by volumio** [comment]
@balbuze can you check and eventually merge? 

@reshnm thanks for submitting it!

**Comment by balbuze** [comment]
Ok, I'll have a look asap

**Comment by balbuze** [comment]
done for arm! Is there an x86 version?

**Comment by a-i-ks** [comment]
@balbuze thanks for your plugin, I'm currently working on the same plugin for the Philips hue system. @volumio A little request: Could you please remove the nodes_modules folder in the tradfri folder from git repo? Since the repo is so big, cloning takes too long. Thanks :)

**Comment by balbuze** [comment]
@a-i-ks it is not my work... I just published the plugin wrote by reshnm

**Pull request merged**
