### PR TITLE
Radio Paradise update v1.05

### PR DESCRIPTION
**Pull request by marco79cgn**
Added three more flac streams and fixed some bugs

### CODE REVIEW

**Comment by DFPozzi** [comment]
Work fine, thanks!
...but it keeps cutting randomly. I do not know what else to look at!

**Comment by marco79cgn** [comment]
It's running here for hours without drops/cutting. But there are some other users reporting this behaviour as well, even with the old versions. I can't reproduce it at all! It might depend on the geo location or ISP.

**Comment by DFPozzi** [comment]
The cut is not reflected in the log of Volumio?
Can not draw any conclusion from there?

**Comment by marco79cgn** [comment]
Nope, unfortunately I can't see anything suspicious in the volumio logs of these users. 
It even cuts out when they try to play one of these flac files directly. 

For most people it seems to work just fine (like myself).

**Comment by DFPozzi** [comment]
Strange things always happen to me ... never simple.
This in virtual mode, in real mode, everything is ok!

**Comment by DFPozzi** [comment]
The flac file, if I play it in VLC, Media, Open Network Stream, works correctly. If it was an ISP problem or geolocation, it should also fail.

**Comment by marco79cgn** [comment]
Could we please move this discussion to the Forum where it belongs to? It has nothing to do with these changes here and the pull request.

Thanks!

**Comment by DFPozzi** [comment]
Sorry, it's raised in the forum. I raise it again?

**Comment by Ghembs** [comment]
Hello there,

tested the plugin, heard some drops that disappeared after disabling and re enabling the plugin but overall it works fine, therefore I'm going to merge.

**Pull request merged**
