### PR TITLE
ambx: Fixes and improvement

### PR DESCRIPTION
**Pull request by Xerusial**
Fixed a bug where the AmbX plugin could not be uninstalled, if no
AmbX device is connected. It was occuring due to the onStop rejecting
its promise, if the device could not be switched off prior to
uninstalling. It was fixed by onStop always resolving its promise.

Added improvements:
Stability: Color change is now executed with execSync with the
exception onStop. This fixes the lights sometimes not changing color.

Logging: Python logs to syslog and returns error codes.

### CODE REVIEW

**Comment by balbuze** [comment]
TY
Please, can you close this PR because of conflict and send a new one?

**Comment by Xerusial** [comment]
@balbuze This was quick. Thank you so much!

**Comment by balbuze** [comment]
Should be available in minutes in plugin page.
Very nice plugin!

**Comment by Xerusial** [comment]
@balbuze Plugin already shows up, but gives me a 404 not found on http://plugins.volumio.org/plugins/volumio/armhf/miscellanea/ambx/ambx.zip . Do I need to wait some more minutes?

**Comment by balbuze** [comment]
No there is something else wrong with GitHub... Need to dig

**Pull request merged**
