### PR TITLE
new youtube version

### PR DESCRIPTION
**Pull request by sla89**
I have fixed some bugs and implemented user authentication. So the user can now grant volumio via oAuth access to its youtube account and the plugin can then display user related data like the users playlists, subscriptions,....

### CODE REVIEW

**Comment by sla89** [comment]
forgot to increase version number

**Comment by volumio** [comment]
Are you resending?

**Comment by sla89** [comment]
yes - I will create a new one in the evening

**Comment by sla89** [comment]
done

**Pull request closed without merging**
