### PR TITLE
Major update for LastFM

### PR DESCRIPTION
**Pull request by Saiyato**
- Added similar artists/tracks lookup in the browse menu (icon can be changed to match Volumio style, but I'm not good at this)
- The results now perform a search against the library if clicked
- Some cleanup in the logic and better logic for extracting info from streaming services
- Dynamic support for music services (users can maintain them in settings)

### CODE REVIEW

**Comment by balbuze** [comment]
@Saiyato can you fix the conflicting files please. TY

**Comment by Saiyato** [comment]
Hi @balbuze the resolve conflicts button is greyed out, can you tell me where the conflict is?

**Comment by Saiyato** [comment]
I tried removing package.json and adding it again, to no avail I'm afraid

**Comment by kionez** [comment]
Is there any chance that it will be included in a future update\release?

**Comment by balbuze** [comment]
Hi! I can't merge due to conflicting package. I don't know how and why. Maybe remove package.json, create a PR, add the file and create a new PR. Or if someone else can help...

**Pull request closed without merging**
