### PR TITLE
Update LMS package link

### PR DESCRIPTION
**Pull request by Saiyato**
Reverted to the default -> 7.9.1
Will look for a fashionable way to point to 7.9.2 (nightly)

### CODE REVIEW

**Comment by Saiyato** [comment]
The multi-fix is imperative in addition to the package link.

**Comment by volumio** [comment]
Tested it and it does not work. Config seems not to have written.
Please:
- Remove the enabled\disabled from conf (and from restartservice). The plugin is started\stopped by volumio plugin manager.
- Write the configuration everytime you need to start\restart the plugin. Make sure the configuration is written, then on the callback function start the plugin.
- If possible write the conf under /tmp folder and instruct LMS to look there (we avoid writing too much stuff
- IF possible try to reduce node modules usage.

For your reference, the logs of the failed start (from fresh volumio install) I suggest you to try with a fresh install as well.
Dec 06 11:33:44 volumio volumio[913]: info: CoreCommandRouter::executeOnPlugin: system , getShowWizard
Dec 06 11:33:44 volumio sudo[13937]: pam_unix(sudo:session): session closed for user root
Dec 06 11:33:44 volumio volumio[913]: info: CoreCommandRouter::executeOnPlugin: multiroom , getMultiroom
Dec 06 11:33:44 volumio volumio[913]: info: Listing playlists
Dec 06 11:33:44 volumio sudo[13946]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ifconfig wlan0
Dec 06 11:33:44 volumio sudo[13946]: pam_unix(sudo:session): session opened for user root by (uid=0)
Dec 06 11:33:44 volumio sudo[13946]: pam_unix(sudo:session): session closed for user root
Dec 06 11:33:48 volumio volumio[913]: info: [{"prettyName":"Logitech Media Server","name":"lms","category":"music_service","version":"1.0.15","icon":"fa fa-music","enabled":false,"active":false}]
Dec 06 11:33:53 volumio sudo[14017]: volumio : TTY=pts/0 ; PWD=/home/volumio/volumio-plugins/plugins/music_service/logitechmediaserver ; USER=root ; COMMAND=/bin/journalctl -f
Dec 06 11:33:53 volumio sudo[14017]: pam_unix(sudo:session): session opened for user root by volumio(uid=0)
Dec 06 11:33:56 volumio volumio[913]: info: Enabling plugin lms
Dec 06 11:33:56 volumio volumio[913]: info: Loading plugin "lms"...
Dec 06 11:33:57 volumio volumio[913]: info: LMS initiated
Dec 06 11:33:57 volumio volumio[913]: info: PLUGIN START: lms
Dec 06 11:33:57 volumio sudo[14044]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/systemctl restart logitechmediaserver
Dec 06 11:33:57 volumio sudo[14044]: pam_unix(sudo:session): session opened for user root by (uid=0)
Dec 06 11:33:57 volumio systemd[1]: Starting Logitech Media Server Daemon...
Dec 06 11:33:57 volumio systemd[1]: Started Logitech Media Server Daemon.
Dec 06 11:33:57 volumio sudo[14044]: pam_unix(sudo:session): session closed for user root
Dec 06 11:33:57 volumio volumio[913]: info: logitechmediaserver started
Dec 06 11:33:57 volumio volumio[913]: info: Done.
Dec 06 11:33:57 volumio squeezeboxserver[14062]: modules.conf not found at /usr/share/perl5/Slim/bootstrap.pm line 353.
Dec 06 11:33:57 volumio squeezeboxserver[14062]: BEGIN failed--compilation aborted at /usr/sbin/squeezeboxserver line 173.
Dec 06 11:33:57 volumio systemd[1]: logitechmediaserver.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 06 11:33:57 volumio systemd[1]: Unit logitechmediaserver.service entered failed state.
Dec 06 11:34:10 volumio volumio[913]: info: CoreCommandRouter::getUIConfigOnPlugin
Dec 06 11:34:10 volumio volumio[913]: info: Loaded the previous config.
Dec 06 11:34:10 volumio volumio[913]: info: ## populating UI...
Dec 06 11:34:10 volumio volumio[913]: info: 2/2 LMS settings loaded
Dec 06 11:34:10 volumio volumio[913]: info: Populated config screen.
Dec 06 11:34:14 volumio volumio[913]: info: [{"prettyName":"Logitech Media Server","name":"lms","category":"music_service","version":"1.0.15","icon":"fa fa-music","enabled":true,"active":true}]
Dec 06 11:34:27 volumio volumio[913]: info: CoreCommandRouter::getUIConfigOnPlugin
Dec 06 11:34:27 volumio volumio[913]: info: Loaded the previous config.
Dec 06 11:34:27 volumio volumio[913]: info: ## populating UI...
Dec 06 11:34:27 volumio volumio[913]: info: 2/2 LMS settings loaded
Dec 06 11:34:27 volumio volumio[913]: info: Populated config screen.

**Comment by volumio** [comment]
On top of that, installing LMS breaks apt 

You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 build-essential : Depends: libc6-dev but it is not going to be installed or
                            libc-dev
                   Depends: gcc (>= 4:4.9.1) but it is not going to be installed
                   Depends: g++ (>= 4:4.9.1) but it is not going to be installed
                   Depends: make
                   Depends: dpkg-dev (>= 1.17.11) but it is not going to be installed
 logitechmediaserver : Depends: libio-socket-ssl-perl but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

**Comment by Saiyato** [comment]
1. There are some optimalisations to be done yes, I don't think the config is needed anymore, will see if I can delete it.
2. I can try to reduce the number of node modules as well yes, will remove everything and have it install the necessary ones only, then update the package.json
3. apt-get -f install is already in the script, see line 39, but I will move it past the other installation dependencies instead.

On it!

**Comment by Saiyato** [comment]
Addressed all three remarks:

1. Configuration is removed altogether, it didn't add anything really;
2. Only four modules remain, which are actually used;
3. The apt-get install -f only needed a -y parameter, which I added, plus I moved it a bit down-stream to ensure all dependencies are met.

**Comment by balbuze** [comment]
hi! what about this?

**Comment by Saiyato** [comment]
This one should be good, it fetches a new version of LMS and the scripts have been minimised for clarity.

**Pull request merged**
