### PR TITLE
Duo

### PR DESCRIPTION
**Pull request by Saiyato**
@balbuze & @volumio,

As per request, added x86 support (compiled and tested on my two laptops), no difference and both are working as intended. 

Test devices:
- Lenovo T60p 
- HP 6820s

I could even swap the USB stick between devices and it still worked.

Also fixed a timing issue where sometimes a bad PAM jump occurred, had to do with asynchronous actions, all critical steps are synchronous now.

### CODE REVIEW

**Comment by balbuze** [comment]
hi!
have you tested on laptop running volumio x86?

**Comment by Saiyato** [comment]
> hi!
> 
> have you tested on laptop running volumio x86?

Yes, both install and uninstall work on my test devices. I only test on Volumio images 😄

**Comment by Saiyato** [comment]
Merci!

**Comment by balbuze** [comment]
:+1:

**Comment by balbuze** [comment]
I had to reduce the description limited at 200 char max

**Comment by Saiyato** [comment]
Check, I'll keep that in mind. 

One question though, can we also replace the light bulb icon in the store with a shield? Just for uniformity (and aesthetics of course) 😄 Thanks in advance.

**Comment by balbuze** [comment]
The icon can be defined in package.json as far as I can remember (I can't check now). Have a look at the equalizer.

**Comment by Saiyato** [comment]
Hi @balbuze , I added the fa-shield icon and it shows correctly when installed, just not in the store.

**Comment by Saiyato** [comment]
Hi @balbuze ,

Not sure if I can influence this, but the icon is set in:  http://plugins.volumio.org/plugins/volumio/armhf/plugins.json
See the fa-lightbulb-o icon:
```
{
	"author": "Saiyato",
	"description": "Duo Unix with Pluggable Authentication Modules (PAM) support provides a secure and customizable method for protecting Unix and Linux logins. Pre-compiled package for 32-bit ARM and x86 machines.",
	"details": "DUO authenticating SSH sessions",
	"icon": "fa-lightbulb-o",
	"license": "GNUv2",
	"name": "duo",
	"prettyName": "Cisco DUO",
	"screenshots": [
		{
			"image": "",
			"thumb": ""
		}
	],
	"updated": "4-10-2020",
	"url": "http://plugins.volumio.org/plugins/volumio/armhf/miscellanea/duo/duo.zip",
	"version": "1.2.3"
}
```

**Comment by balbuze** [comment]
Just push a PR with the one you'd like

**Comment by Saiyato** [comment]
Hi @balbuze ,

I'm not sure what's going on, it should already be in the file: https://github.com/Saiyato/volumio-plugins/blob/86c68b4dbe434b5c96e2f56cbe31b3b62fa18210/plugins/miscellanea/duo/package.json

I'm seeing more lightbulbs, all latest additions (as the list is not ordered alphabetically) have the lightbulb in the plugins.json file.
All plugins as of date x have the lightbulb in plugins.json, installing the plugin will show the authors chosen icon (installed plugins tab). Does that mean we should add both the plugin and update plugins.json?

**Comment by balbuze** [comment]
Not sure but it seems it is the first icon used when publishing the first time the plugin. Don't worry, I'll update this evening.

**Comment by Saiyato** [comment]
Hi,

Just checking whether I can help in any way, all of the commits already included the fa-shield icon, but maybe I forgot a step somewhere. Then I can PR the gh-pages for other authors and explain the necessary steps :smile:

**Comment by balbuze** [comment]
I fixed the icon in the store and published v 1.2.5 ;-)

**Comment by Saiyato** [comment]
Awesome! Many thanks

**Pull request merged**
