### PR TITLE
backup_restore plugin final

### PR DESCRIPTION
**Pull request by macmpi**

### CODE REVIEW

**Comment by macmpi** [comment]
@volumio conflict has been generated by recent plugin.json format change (easier to read though!)
Tried to resolve by pulling my plugin from list and then adding back where it was, but no success.

Overall, any interest in integrating this plugin?
It has been in PR for few months: let me know if no interest and I will close, or if some changes are needed to do so (was generated but Volumio2 embedded plugin tool).
Thanks.

**Comment by volumio** [comment]
Sorry but can't accept this PR, for the following reasons:
- node_modules are included, and they should not 
- The diff is huge: lots of files are changed

To have it merged please:
- Do a PR of just the code in the master branch (but align your branch first)
- Do not include node_modules in the PR

Thanks!

**Comment by macmpi** [comment]
Ok, thanks for the note: will do.

As side note, we'd probably need to improve built-in plugin development tool, so that npm install (& plugin zip compression which need dependencies) happens in target plugin directory, not in branch to be submitted. This would ease final PR submit.
What do you think?

**Comment by macmpi** [comment]
If I submit PR with `master`, you will not get `plugins.json` nor the zip archive.
I thought I needed to submit the `gh-pages`: will you produce them yourself?

I fixed the json problem and nodes-modules [in my repo](https://github.com/macmpi/volumio-plugins/tree/gh-pages), but can't find a way to remove all those fast-forwardable changes.
```
git remote show upstream
* remote upstream
  Fetch URL: https://github.com/volumio/volumio-plugins.git
  Push  URL: https://github.com/volumio/volumio-plugins.git
  HEAD branch: master
  Remote branches:
    gh-pages tracked
    master   tracked
  Local refs configured for 'git push':
    gh-pages pushes to gh-pages (fast-forwardable)
    master   pushes to master   (fast-forwardable)
```
seems to be ok.

and:
```
volumio@volumio:~/volumio-plugins$ git fetch upstream gh-pages
From https://github.com/volumio/volumio-plugins
 * branch            gh-pages   -> FETCH_HEAD
volumio@volumio:~/volumio-plugins$ git pull upstream gh-pages
From https://github.com/volumio/volumio-plugins
 * branch            gh-pages   -> FETCH_HEAD
Already up-to-date.
volumio@volumio:~/volumio-plugins$ git push --force origin gh-pages
Username for 'https://github.com': macmpi
Password for 'https://macmpi@github.com':
Everything up-to-date
```
Tried `git pull --rebase upstream gh-pages` but it chokes a lot as some files were removed/re-added in all thoses changes. 
Appreciate any help

**Comment by volumio** [comment]
Yes, all I need is the source in the plugin master branch, then I test it and prepare the package.

**Comment by macmpi** [comment]
I think https://github.com/volumio/volumio-plugins/pull/110 should be ok now.
Let me know.

**Pull request closed without merging**
