### PR TITLE
Dependency patch

### PR DESCRIPTION
**Pull request by Saiyato**
This fixes the unmatched dependency errors when users try to install the plugin. The previous version would fetch the latest SnapCast release, which needs a newer distro version. This patch will install the working 0.15.0 release from the binaries directory in the plugin.

Also sanitized unused files/dirs.

### CODE REVIEW

**Comment by Saiyato** [comment]
Hi,

I'm not sure why I'm getting conflicts, the LastFM plugin also suffered from this. The package.json only updates a version number and the other files are being removed.

Can you advise?

**Comment by balbuze** [comment]
to be honnest, I don't see what happens. Maybe you could try to clone this repo in a new folder, add your modified files and try to send a PR. What do you think?

**Comment by balbuze** [comment]
@Saiyato This PR is still blocked due to files conflict.
And what version of librespot do you use? For info, the fork used for volspotconnect2 is downloaded by the install script from https://github.com/ashthespy/Vollibrespot

**Comment by fatalglitch** [comment]
Can we get this merged? This is breaking any current versions of Volumio with Snapcast

**Comment by balbuze** [comment]
cant merge it with such confilct, sorry

**Pull request closed without merging**
