### PR TITLE
NanoSound plugin v1.7 (for NanoSound DAC2)

### PR DESCRIPTION
**Pull request by nanomesher**
Support configuration of Display
Support button configs for NanoSound DAC2 

https://nanomesher.com/its-here-nanosound-dac-2/

### CODE REVIEW

**Comment by balbuze** [comment]
I get a error while packging the plugin : 
`volumio plugin package

This command will create a package with your plugin

Compressing the plugin
No modules found, running "npm install"
/lib/node_modules/npm/node_modules/gauge/plumbing.js:21
Ploj�a�0[bw�Tg0{<ej0G��=�^��d�"2�x�N/j
                                      �w�R	a�
    ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/lib/node_modules/npm/node_modules/gauge/index.js:2:16)
Error installing node modules: Error: Command failed: /usr/local/bin/npm install
/lib/node_modules/npm/node_modules/gauge/plumbing.js:21
Ploj�a�0[bw�Tg0{<ej0G��=�^��d�"2�x�N/j
`
can you check please. TY

**Comment by nanomesher** [comment]
This is strange. We have never seen this and could not reproduce it.

Below works using raspberry pi 3B+ and volumio 2.572.

1.  git clone https://github.com/nanomesher/volumio-plugins.git
2. cd volumio-plugins/
3. git checkout nanosoundcd_v1.1
4. cd plugins/music_service/nanosound_cd
5. volumio plugin package

Manually ftp the nanosound_cd folder and do a volumio plugin package also worked.

Both worked and zip file was created.

Can you please give it a try and see?

Thanks very much.

**Comment by volumio** [comment]
Don't worry, I just published it and I managed to install modules without an issue

**Comment by nanomesher** [comment]
thanks very much!

**Pull request merged**
