### PR TITLE
ambx: Add fan control

### PR DESCRIPTION
**Pull request by Xerusial**
Add equalizer sliders to control the fan speed of the ambx
system environment fans.

### CODE REVIEW

**Comment by balbuze** [comment]
The plugin does not appears active when activated. Check if a promise is resolved at onStart stage

**Comment by Xerusial** [comment]
> The plugin does not appears active when activated. Check if a promise is resolved at onStart stage

Did you have the old version of it installed before and uninstalled and reinstalled it? Because I changed the name of the python executable from ambx_set_color->ambx_control. But if you had a running version before, Volumio somehow cached the index.js code and executes the old code, therefore searching for ambx_set_color. If you see something like "May 23 09:36:28 volumio volumio[1026]: /bin/sh: 1: ambx_set_color: not found" in the logfile, just do a "volumio vrestart".

I did also mention that here: https://community.volumio.org/t/plugin-philips-ambx/47315/2?u=xerusial

**Comment by balbuze** [comment]
No, it is afresh install. I don't have ambx hw but check by disabling the plugin(ok) then enabling it (nok).

**Comment by Xerusial** [comment]
> No, it is afresh install. I don't have ambx hw but check by disabling the plugin(ok) then enabling it (nok).

https://github.com/volumio/volumio-plugins/pull/585 here is the fix.

**Pull request merged**
