### PR TITLE
Raspdac plugin

### PR DESCRIPTION
**Pull request by JedS**
Finally, publish a proper version of the plugin.
This plugin provide Audiophonics Raspdac power button and OLED configuration management

### CODE REVIEW

**Comment by JedS** [comment]
Do you test the screen with another tools ( like PydPiper) ?
My first Audiophonics Raspdac got a broken OLED and it did show waste as yours.
Audiophonics  send me a new screen and now, everything is ok.
I can reproduce the problem with the shutdown button... it's a minor bug.
Could you please create a new issue on the raspdac plugin page for the software shutdown button ...

**Comment by mskerwiderski** [comment]
I thought the same and got a second display from my seller. But both displays (Winstar model) do not work and show same waste. But both work with Max2Play-Image and Display-Plugin. So I think the displays are not broken. BTW (maybe this helps): Volumio is set to german language.
Great that you can fix power button bug. I will open an issue for it.

**Comment by JedS** [comment]
@mskerwiderski Any chance you try test the 0.0.7 version ?
I updates the lcd module to the latest version and display a welcome message when lcd display is ready.
I do not yet make a pull request for this version. It has been post on my fork for now.

**Comment by mskerwiderski** [comment]
Thank you for your update!
I deinstalled the old version and installed version 0.0.7 via ssh. But unfortunately nothing has changed. The display shows still waste and also on the shut down does not work.

BTW: I tried this Version:
https://github.com/volumio/volumio-plugins/raw/7f60575cddedc1e8623239ae851c33fa3ba75240/plugins/volumio/armhf/user_interface/raspdac/raspdac.zip

Best regards
Michael


________________________________
Von: JedS <notifications@github.com>
Gesendet: Dienstag, Juli 31, 2018 3:54 PM
An: volumio/volumio-plugins
Cc: Michael S.; Mention
Betreff: Re: [volumio/volumio-plugins] Raspdac plugin (#245)


@mskerwiderski<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmskerwiderski&data=02%7C01%7C%7C1312c96a3d74408da56b08d5f6ed31db%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636686420954046447&sdata=HDSmXllXqStyn1umfcW0PnRlKqfn%2FSvLtm0uK9wKvnA%3D&reserved=0> Any chance you try test the 0.0.7 version ?
I updates the lcd module to the latest version and display a welcome message when lcd display is ready.
I do not yet make a pull request for this version. It has been post on my fork for now.

**Comment by Ghembs** [comment]
Hi there,

sorry, since compatibility problems still persist I can't merge this PR.

**Pull request closed without merging**
