### PR TITLE
Patched instantiation after boot

### PR DESCRIPTION
**Pull request by Saiyato**
There was a wrongful comparison, this caused the encoders not to initialize after boot.

### CODE REVIEW

**Comment by volumio** [comment]
Hi, can you solve the conflict?

**Comment by Saiyato** [comment]
I'm not sure why, but the requiredConfig.json file was needed for the merge. But it's not used, just an empty file... weird stuff

Anyways, should be solved @volumio :)

**Comment by Saiyato** [comment]
@volumio can this one be merged? It solves initialisation after reboot issues, thanks.

**Comment by balbuze** [comment]
@Saiyato hi! you closed your PR. You have new fix ? let  me know

**Comment by Saiyato** [comment]
Merci!

**Pull request merged**
