### PR TITLE
RotaryEncoder II Plugin - Install issue fixed

### PR DESCRIPTION
**Pull request by 7h0mas-R**
Install is now working
Bug was related to loading of international strings in the GUI after install when calling the settings page. 
Tested on 3 RPis now and working on all of them. Also, the bug was finally 100% reproducible, so I think it is really fixed now.

### CODE REVIEW

**Comment by balbuze** [comment]
Hello,
Not better...
Enabling fails
```
Sep 04 10:07:57 volumio-v2.874 volumio[10403]: info: Enabling plugin rotaryencoder2
Sep 04 10:07:57 volumio-v2.874 volumio[10403]: info: Loading plugin "rotaryencoder2"...
Sep 04 10:07:57 volumio-v2.874 volumio[10403]: error: !!!! WARNING !!!!
Sep 04 10:07:57 volumio-v2.874 volumio[10403]: error: The plugin user_interface/rotaryencoder2 failed to load, setting it to stopped. Error: Error: Cannot find module 'onoff'
Sep 04 10:07:57 volumio-v2.874 volumio[10403]: error: Stack trace: Error: Cannot find module 'onoff'
Sep 04 10:07:57 volumio-v2.874 volumio[10403]: at Function.Module._resolveFilename (module.js:547:15)
Sep 04 10:07:57 volumio-v2.874 volumio[10403]: at Function.Module._load (module.js:474:25)
Sep 04 10:07:57 volumio-v2.874 volumio[10403]: at Module.require (module.js:596:17)
Sep 04 10:07:57 volumio-v2.874 volumio[10403]: at require (internal/module.js:11:18)
Sep 04 10:07:57 volumio-v2.874 volumio[10403]: at Object.<anonymous> (/data/plugins/user_interface/rotaryencoder2/index.js:9:14)
Sep 04 10:07:57 volumio-v2.874 volumio[10403]: at Module._compile (module.js:652:30)
Sep 04 10:07:57 volumio-v2.874 volumio[10403]: at Object.Module._extensions..js (module.js:663:10)
Sep 04 10:07:57 volumio-v2.874 volumio[10403]: at Module.load (module.js:565:32)
Sep 04 10:07:57 volumio-v2.874 volumio[10403]: at tryModuleLoad (module.js:505:12)
Sep 04 10:07:57 volumio-v2.874 volumio[10403]: at Function.Module._load (module.js:497:3)
Sep 04 10:07:57 volumio-v2.874 volumio[10403]: at Module.require (module.js:596:17)
Sep 04 10:07:57 volumio-v2.874 volumio[10403]: at require (internal/module.js:11:18)
Sep 04 10:07:57 volumio-v2.874 volumio[10403]: at PluginManager.loadCorePlugin (/volumio/app/pluginmanager.js:147:29)
Sep 04 10:07:57 volumio-v2.874 volumio[10403]: at Promise._successFn (/volumio/app/pluginmanager.js:1543:19)
Sep 04 10:07:57 volumio-v2.874 volumio[10403]: at nextTickCallback (/volumio/node_modules/kew/kew.js:47:28)
Sep 04 10:07:57 volumio-v2.874 volumio[10403]: at _combinedTickCallback (internal/process/next_tick.js:131:7)
```
no UI loads
Uninstall fails...
Did you test your work before sending PR?

**Comment by 7h0mas-R** [comment]
Hi Balbuze,

I’m really, really sorry. I tested it on three different RPi models, one of them with a freshly flashed SD image.
Analyzing your log it looks to be an issue with the `npm install` of the `onoff` package.
But there, I think I need your advice - since `onoff` is really a classic on npm and also used in other plugins and I am not so deeply into npm. 
Besides, it did not look like this when I made the package back in June. See details below.

### Problem Description
My code is functional, but npm install does not correctly install `onoff`, so it seems.

- 'onoff' is listed in `package.json` as `"onoff": "^6.0.1“`. So it should install automatically.
- The Zip in my ghpages Repo has working modules inside (see the link in my test workflow). 
- When I download my plugin zip and _manually remove_ the `.\node_modules` folder, the `volumio plugin install` runs the automatic `npm install`, but that throws an error when it tries to install `onoff` (full error log below). When I look into 'node_modules' folder, it is indeed missing.
- That might be the reason for the issue, you are seeing `(error: Stack trace: Error: Cannot find module 'onoff')`. 
- I tried to change the dependencies to the most recent version 6.0.3 of `onoff` but it still fails. I also tried 6.0.0, which is used on 'remotepi' plugin and 1.2.0, which is used on the original 'rotaryencoder' plugin by Saiyato. Both give me the same error.
- Since the error messages revolve around issues with make, I did a `sudo apt-get update` and a `sudo apt-get install build-essentials` but it will not install giving me an error about `unmet dependencies` for gcc, g++ and dpkg-dev (see second log below)
- This is completely new behavior. When I ran `sudo apt-get install build-essentials` in the past on a fresh install, it always worked.
- I also tried to `wget`the 'remotepi' plugin, delete its node_modules folder and run install, but that one also fails (and it is a released plugin)
- I'm at a loss now - `onoff`is a real classic in npm - not sure what to do now, especially since it seemed to load fine in the past (as the working package inside my own ZIP file shows)
- You are probably a pro with npm compared to me being a complete newbie - can you give advice? It seems not to be related to my code anymore, I fear.

### Error Log from `npm install`
Not sure what all of them mean, but my understanding was, that it should not be required to start messing with 
```
This command will install the plugin on your device

Compressing the plugin
No modules found, running "npm install"
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.19.118-v7+
gyp ERR! command "/bin/node" "/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/volumio/rotaryencoder2/node_modules/onoff/node_modules/epoll
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN rotaryencoder2@1.0.6 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! epoll@4.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the epoll@4.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/volumio/.npm/_logs/2021-09-04T20_21_35_115Z-debug.log
Error installing node modules: Error: Command failed: /usr/local/bin/npm install --production
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.19.118-v7+
gyp ERR! command "/bin/node" "/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/volumio/rotaryencoder2/node_modules/onoff/node_modules/epoll
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN rotaryencoder2@1.0.6 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! epoll@4.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the epoll@4.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/volumio/.npm/_logs/2021-09-04T20_21_35_115Z-debug.log

/bin/mv: cannot stat '*.zip': No such file or directory
child_process.js:644
    throw err;
    ^

Error: Command failed: /bin/mv *.zip /tmp/plugins/rotaryencoder2.zip
/bin/mv: cannot stat '*.zip': No such file or directory

    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at install (/volumio/pluginhelper.js:689:9)
    at Object.<anonymous> (/volumio/pluginhelper.js:751:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
```

And here the error log of the `sudo apt-get install build-essentials`:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 build-essential : Depends: gcc (>= 4:4.9.1) but it is not going to be installed
                   Depends: g++ (>= 4:4.9.1) but it is not going to be installed
                   Depends: dpkg-dev (>= 1.17.11) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

### My Test Workflow
In case my assumption above is not correct, here is the test-process and zip file I used for verifying that it works. Maybe you can give me a hint, what I might be doing wrong still.
1. Download and install Volumio 2.907 on SD
2. Start RPi with the fresh SD connected to LAN and configure
3. Activate SSH and log in
4. Follow the [instructions for installing unofficial plugin](https://volumio.github.io/docs/Plugin_System/Plugin_System_Overview.html):
    1. Download the plugin with `wget https://github.com/7h0mas-R/volumio-plugins/blob/gh-pages/plugins/volumio/armhf/user_interface/rotaryencoder2/rotaryencoder2.zip?raw=true -O rotaryencoder2.zip`
    2. Creat temp folder `mkdir rotaryencoder2 `
    3. Unzip with `miniunzip rotaryencoder2.zip -d ./rotaryencoder2`
    4. `cd rotaryencoder2`into folder
    5. Install with `volumio plugin install`
    6. Go to the Web UI, section 'Plugins'. It shows up as installed. Activate it. I get a toast message 'Plugin successfully installed'. 
    7. Open 'Settings' make some settings and save.

I am out of ideas now, will go to sleep and see if I find more time to check on older versions tomorrow.

Thanks for advice and guidance,
Thomas

**Comment by 7h0mas-R** [comment]
__update:__ Tonight I had the idea to check which version of gcc is installed on my (working) development system.
(Raspbian 4.9.2-10+deb8u1) and which one it tries to install on the fresh test system (gcc-4.9 (>= 4.9.2-1~)).

I cannot install this on the fresh test system anymore. Some googling brought me to this thread on the Volumio forum:
[Cannot install build-essential package](https://community.volumio.org/t/cannot-install-build-essential-package/46856?u=t0mr0)

**Comment by balbuze** [comment]
Hello!
Good news! It is published,
I reflashed a version v2.874, installed build-essential and voila!
Sorry for that and thanks for your plugin!

**Comment by 7h0mas-R** [comment]
Thanks a lot!
Was really shocked when I received your message yesterday. I feel really relieved now😀

**Pull request merged**
