### PR TITLE
Major update lastfm

### PR DESCRIPTION
**Pull request by Saiyato**
- Major code clean up
- Supports more services
- Fixed some crashes that shouldn't have happened in the first place
- Removed node_modules from master

NOTE: more changes coming, but still testing heavily.

### CODE REVIEW

**Comment by Saiyato** [comment]
This update includes radio_paradise and 80s80s support by Marco

**Comment by balbuze** [comment]
is it still ok to merge?

**Comment by Saiyato** [comment]
Hi there,

Yes, these changes should prevent some crashes, I'm still investigating a more robust approach and artist lookup (similar artists/tracks). But this one is safe to merge.

**Comment by Saiyato** [comment]
Thanks for the merge! Will test the procedure asap.

**Comment by Saiyato** [comment]
It's working, but I need to revise my patch for the radio paradise and 80s80s radio stations. I will create a new PR for that.

**Comment by balbuze** [comment]
Ok. I wait for the x86 version

**Pull request merged**
