### PR TITLE
backup_restore final

### PR DESCRIPTION
**Pull request by macmpi**
Should be good now.
Only tested on `armhf`, but no reason it would not work on any other platform

FWIW, prepared the `plugins.json` section if you want:
```
				{
					"prettyName": "Backup & Restore Data",
					"icon": "fa-floppy-o",
					"name": "backup_restore",
					"version": "0.7.2",
					"url": "http://volumio.github.io/volumio-plugins/plugins/volumio/armhf/system_controller/backup_restore/backup_restore.zip",
					"license": "ISC",
					"description": "This plugin allows User to locally backup volumio data (playlists, settings, etc) and restore later",
					"details":"<h4>Backup & Restore Plugin</h4><br>Locally back-up and restore Volumio data<br><br>Choose which sets of data you want to archive (queue, playlist, Favourites, Configuration, Album Art), and hit backup button:<br>Generated archive file will then be available from Volumio SMB share.<br>That file may be copied & put-back in similar location on another (or re-imaged) device for restore.",
					"author": "macmpi",
					"screenshots": [
						{
							"image": "",
							"thumb": ""
						}
					],
					"updated": "10-8-2017"
				},

```

### CODE REVIEW

**Comment by macmpi** [comment]
@volumio is this PR more acceptable than former #88 ?
Thanks for feedback.

**Comment by volumio** [comment]
That's just perfect, thanks! I'll test and eventually publish if all is ok

**Comment by macmpi** [comment]
Let me know if you find any issue hampering publication

**Comment by volumio** [comment]
Published! Congratulations for the great work.
Few suggestions for further improvements:
- Signal the backup creation with a modal as you do with the restore
- Tell explicitly in the modal that the button will reboot the device
- Backup also the mpd database, and check the proper audio device is selected on reboot
- Use the openUrl element in the Ui to allow an easy download of the backup archive:
https://volumio.github.io/docs/Plugin_System/UI_Configuration_Pages.html

**Comment by macmpi** [comment]
Thanks @volumio for your note and suggestions.
About modals: would this https://github.com/volumio/Volumio2/pull/1357 or any other approach help to facilitate such messages localization?

I think I'm pondering upon how/if I should back-up some core linux setting files (wpasupplicant.conf, dhcpcd.conf, mpd.conf, etc...) in addition to Volumio prefs, and which ones...
The issue is that on restore, just restoring Volumio2 prefs (like networking stuff) may not re-enable actual settings: user then needs to flip/save some settings for Volumio app to write system files...
I could save/restore some critical system config files, but I need to make sure which ones I do/do not.

Ideally Volumio would have a **unified API to apply any setting change**, and I could call it after I restore Volumio2 prefs to apply into system settings, but it does not seem to be the case...
I had hoped this would have come with Wizard work, but it does not seem to.

Any suggestion to avoid creating setup mess in config files between Volumio settings and their Linux system counterparts?

Thanks.

**Pull request merged**
