### PR TITLE
Delete UIconfig.json

### PR DESCRIPTION
**Pull request by Saiyato**
Double config file, probably a merge conflict. Note the small letter c as opposed to the required capital C.

Note: this renders the config useless, it's not a functional patch, but a required technical one.

### CODE REVIEW

**Comment by Saiyato** [comment]
@volumio is it possible to merge this one quickly? This will effectively enable the plugin again. :)

**Comment by Saiyato** [comment]
The update was just EOL: Windows > Unix, still mergable without problems.

**Comment by balbuze** [comment]
hi!
do we need to update version number?

**Comment by Saiyato** [comment]
Hi there,

No, it was a merge conflict I guess, nothing changed in code. Thanks for the merge!

**Pull request merged**
