### PR TITLE
Radio paradise  v1.1.0

### PR DESCRIPTION
**Pull request by marco79cgn**
The plugin is now using the new static flac streams offered by Radio Paradise to avoid playback interruptions in Volumio

### CODE REVIEW

**Comment by marco79cgn** [comment]
Hi! 
The update (1.1.0) doesn't show up in the Volumio GUI yet. It's still 1.0.5 there. Did I make a mistake?

**Comment by volumio** [comment]
No, we need to publish it after you make a pull request. Just published it ;)

**Comment by marco79cgn** [comment]
Thank you for the clarification. :)
I'm also not sure whether I have to include the packaged zip-file or not. It's there but maybe not necessary?

**Comment by volumio** [comment]
You should not include the .zip (it hogs the repo with unnecessary files)

**Comment by marco79cgn** [comment]
OK, thanks. I added it to my gitignore.

**Comment by phatpaul** [comment]
@marco79cgn thanks for a great plugin, but why did you remove the Rock and Groovy mix stations in version 1.10?
Version 1.05 was working great for me and is still installed on one of my Pis, but any new Pis that I install don't have the other stations.  

Can I install the old version plugin on a new Pi?  Or can I add the stations back? 
Can I just edit ```/data/plugins/music_service/radio_paradise/radio_stations.json```
and add them from https://radioparadise.com/listen/stream-links ?

**Comment by marco79cgn** [comment]
@phatpaul 
Actually it was Radio Paradise who removed them temporarily a few months ago. That's why I removed them as well. I'll update the plugin as soon as possible. It's not just the stream url in radio_stations.json but I will make the plugin more flexible so that it's enough to update this file in the future.

**Pull request merged**
