### PR TITLE
Major update rotaryencoder

### PR DESCRIPTION
**Pull request by Saiyato**
Solves most of the erratic behaviour

### CODE REVIEW

**Comment by Saiyato** [comment]
As said this one solves most of the annoying erratic behaviour, there are still some delays, but they shouldn't be erratic anymore.

**Comment by balbuze** [comment]
I'm testing the plugin. something is wrong with your package onoff-rotary. Can you  check please? TY

**Comment by Saiyato** [comment]
Hi @balbuze ,

I was able to install it without problems, can you tell me what it is you are seeing? If you mean the entry in package.json, that's the only way to force a download of a forked package that is not in the npm store. I have not yet figured out how to publish to the store.

**Comment by balbuze** [comment]
To test, remove node_modules folder. Then use "volumio plugin install". When you enable the plugin it hangs volumio. Sudo journalctl -f shows it can't find on-off library. I tested on a rpi2.

**Comment by Saiyato** [comment]
Weird, can you send me the zipfile of the plugin without the node modules?
When I install I get the following (without errors):
```
volumio@volumiogarden:~/svn/rotaryencoder$ volumio plugin install

This command will install the plugin on your device

Compressing the plugin
No modules found, running "npm install"
Plugin succesfully compressed
Progress: 10
Status :Downloading plugin
Progress: 30
Status :Creating folder on disk
Progress: 40
Status :Unpacking plugin
Progress: 50
Status :Checking for duplicate plugin
Progress: 60
Status :Copying Plugin into location
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 90
Status :Adding plugin to registry
Progress: 100
Status :Plugin Successfully Installed
Done!
```
Is there a way I can actually test my PR, because I tested against my forked repo.

**Comment by balbuze** [comment]
yes the plugin install fine. But have you tried to enable it?

**Comment by Saiyato** [comment]
Yes, I'm getting the following (on a Pi2B with HifiBerry AMP)
```
Mar 25 21:31:05 volumiogarden volumio[21445]: info: Enabling plugin rotaryencoder
Mar 25 21:31:05 volumiogarden volumio[21445]: info: Loading plugin "rotaryencoder"...
Mar 25 21:31:05 volumiogarden volumio[21445]: info: Applying required configuration parameters for plugin rotaryencoder
Mar 25 21:31:05 volumiogarden volumio[21445]: info: PLUGIN START: rotaryencoder
Mar 25 21:31:05 volumiogarden volumio[21445]: info: Done.
```

**Comment by Saiyato** [comment]
I update the debug settings:
```
Mar 25 21:36:02 volumiogarden volumio[21445]: info: CALLMETHOD: user_interface rotaryencoder updateDebugSettings [object Object]
Mar 25 21:36:02 volumiogarden volumio[21445]: info: CoreCommandRouter::executeOnPlugin: rotaryencoder , updateDebugSetting
```s

Then I turned the knob on the KY-040 encoder:
```
Mar 25 21:36:13 volumiogarden volumio[21445]: info: [Rotary encoder] Encoder #1 rotated right
Mar 25 21:36:13 volumiogarden volumio[21445]: info: [Rotary encoder] Executing command: /usr/local/bin/volumio volume plus
Mar 25 21:36:13 volumiogarden volumio[21445]: info:
Mar 25 21:36:13 volumiogarden volumio[21445]: ---------------------------- Client requests Volume +
Mar 25 21:36:13 volumiogarden volumio[21445]: info: VolumeController::SetAlsaVolume+
```

**Comment by balbuze** [comment]
Ok. I have to recheck what was wrong.

**Comment by balbuze** [comment]
I think I found the problem.... It is a fresh install and the system miss "build-essential". Sorry ;-)

**Comment by balbuze** [comment]
merged and published!

**Comment by Saiyato** [comment]
Haha, no worries, many thanks for the merge!

**Pull request merged**
