### PR TITLE
Pandora Plugin v2.6.0 Update

### PR DESCRIPTION
**Pull request by truckershitch**
v2.6.0 Update - Queue voodoo, some refactoring, variable type changes, cosmetic bug fixes.  Split off Timer classes and PandoraHandler function to separate modules.

### CODE REVIEW

**Comment by balbuze** [comment]
Hi! Not sure it is a new issue but when the plugin is enabled the first time it does not appears as enabled due to the warning message about email. 
It is due to the fact there is no resolved promise in Onstart function. it should be in the form : 
```
ControllerExamplePlugin.prototype.onStart = function() {
    var self = this;
	var defer=libQ.defer();


	// Once the Plugin has successfull started resolve the promise
	defer.resolve();

    return defer.promise;
};
```
And the same for other function.
 See : https://github.com/volumio/volumio-plugins/blob/master/example_plugin/index.js

**Comment by truckershitch** [comment]
@balbuze:

**Thank you very much!**  That has been bothering me for a while.

I came up with a better [ good login | bad login | change login ] flow.  I've logged in and out, and started the plugin with invalid credentials, and so far it works.  I'll take a break and test more later.

> And the same for other function.
> See : https://github.com/volumio/volumio-plugins/blob/master/example_plugin/index.js

Which other function?  Is it `ControllerPandora.prototype.onStop()` ?

I thought that was working but I will look again.  I probably have a bug in there also.

I should have a better version tomorrow or the day after.  I know there's no pressure.  This damn Covid-19 virus created the perfect time for a project.

**Comment by balbuze** [comment]
Yes Onstop. Let me know when ready 😉

**Comment by kevinkay30** [comment]
I now how Pandora on my on my Raspberry pi (and I am LOVING it) through your instructions.
Thank you 
Thank you
Thank you

**Pull request merged**
