### PR TITLE
Volusonic

### PR DESCRIPTION
**Pull request by foobarjo**
initial merge

### CODE REVIEW

**Comment by Ghembs** [comment]
Hello there,

I'm sorry, plugin seems really interesting but I encountered some problems that made it unusable:

- "Save and test connection" button has no effect, the "save" on options prompts an "undefined" confirmation.
- Buttons of the main menu should be named, the icons are nice but some of them are not immediate.
- I wasn't able to access anything, it could very well have been a mistake on my side but since I received no notifications about that I would have expected a normal behavior. 

Thus I can't merge, tried on raspberry pi with both subsonic and plex.

**Comment by foobarjo** [comment]
Hello, 

Thanks for testing. 

- I did some enhancement on the error handling and you now will have good feedback on what's good or wrong regarding your connection status and your credentials
- Buttons are already named, i wasn't able to reproduce this behavior, but at a time I had some troubles to reload the GUI for translations and I needed to reboot volumio to see labels. Is it your case?
- Originally the plugin was only capable to access tagged music (ID3 functions). It can now also use the standard file based way. To do so, just deactivate the ID3 in the option panel. I hope that was the cause.

**Comment by camg70** [comment]
Hello foobarjo,

I was testing volusonic plugin to my multiroom Volumio project , with subsonic .
Soon I understood why it was not reacting as expected : My subsonic API is >1.13.

Any intentions to update compatibility to newer API?
I have a some programming knowledge. Do you think I could help (with some guide lines from you ) to test newer API , I am absolutly noob on github. 

thanks

**Comment by foobarjo** [comment]
Hello camg70, 
By the way it's API >1.13.0, it was an error in the README. 
Can you post on the volumio forum in the thread dedicated to volusonic (the one you already posted in once) a description of your setup and the issues you encounter?
The thread here is dedicated to discussion around merging the plugin in the master branch of volumio.

Thanks !

**Pull request closed without merging**
