### PR TITLE
Delete package-lock.json

### PR DESCRIPTION
**Pull request by Saiyato**
I believe this PR will contain more that just this change, just trying to see if it'll update automagically.

### CODE REVIEW

**Comment by Saiyato** [comment]
See #319, that one contains the new version. The previous PR was reverted, but I never re-created it.

**Comment by balbuze** [comment]
do we still need this PR?

**Comment by Saiyato** [comment]
Hi @balbuze, only if the package-lock.json file is still in the repo, will try to install from the store right away and check.

**Comment by Saiyato** [comment]
Update: I'm still seeing the package-lock file, it's also there for several other plugins, but not all.
According to documentation it should be there though: https://docs.npmjs.com/files/package-lock.json

So yes, it can be closed :)

**Pull request closed without merging**
