### PR TITLE
Upload DUO plugin

### PR DESCRIPTION
**Pull request by Saiyato**
This plugin adds two-factor authentication (2FA) for SSH sessions to your Volumio device. At this moment there are still some issues when changing the password, as some hard-coded functions require the default password. However, security can be hardened by adding two-factor authentication to (at least) starting SSH sessions.

My Github repo: https://github.com/Saiyato/volumio-duo-plugin

### CODE REVIEW

**Comment by balbuze** [comment]
hello!
Nice job!
But have you tested if volumio still update after the plugin is enabled?

**Comment by Saiyato** [comment]
Hi @balbuze ,

Just upgraded from 2.806 to 2.834 successfully, the necessary files are untouched:
- /etc/pam.d/ssh
- /etc/duo/pam_duo.conf
and the DUO package was not uninstalled (as to be expected of course) ;)

Which means, the solution appears to be upgrade-proof; it will only affect authentication (=add options) for the SSH service. :)

**Comment by balbuze** [comment]
Thanks for testing. Is it supposed to work with x86 too?

**Comment by Saiyato** [comment]
Not yet, I will need to compile for x86, do you know how to compile multi-platform from source? I'd be more than happy to compile, what I did was:

- ./configure --with-pam --prefix=/usr && make
- sudo make install (this creates the necessary directories, because checkinstall fails if I don't do this)
- sudo checkinstall -D make install

Any tips for me?

**Comment by volumio** [comment]
You can do the same on a X86 machine and VolumioX86, is that feasible for you?

**Comment by balbuze** [comment]
I use a x86 VM (virtualbox) wiith volumiox86. It allows to test and compile plugin or anything else

**Comment by balbuze** [comment]
I pushed the arm version ;-)

**Comment by Saiyato** [comment]
Thanks @balbuze ! I just compiled i386 today. I don't think this will work on i686 right? I'm not too familiar with CPU architectures ;) also, I'm pretty sure my laptop should be able to run x64, but the image is only x86. Is there any need for a 64 bit package?

**Comment by balbuze** [comment]
Volumio is only 32bits... No need for x64 now.
i386 should work on i686
Did you test on a x86 image?

**Pull request merged**
