### PR TITLE
Extended uninstall script and fixed config error

### PR DESCRIPTION
**Pull request by Saiyato**
Uninstalling now removes all unnecessary files.

fixes #145

### CODE REVIEW

**Comment by Saiyato** [comment]
Just added SnapCast to the mix.

**Comment by Saiyato** [comment]
Just added another (small) plugin, copied some work by Jedail and minimized it to serve only one purpose (Audiophonics button).

**Comment by Saiyato** [comment]
Small update which fixes LastFM config

**Comment by Saiyato** [comment]
Added another bug fix, this time for the rotary encoder.

**Comment by volumio** [comment]
There are conflicts in this PR, can you solve them?

**Comment by Saiyato** [comment]
Done, didn't know how that worked before. Now I do :)
Sorry for the inconvenience

**Comment by volumio** [comment]
Thanks!

**Comment by Saiyato** [comment]
Add initial pydPiper plugin

**Comment by Saiyato** [comment]
Updated LastFM plugin to enable scrobbling for Radio Paradise

**Comment by Saiyato** [comment]
Added reworked pydpiper plugin

**Pull request closed without merging**
