### PR TITLE
New version of youtube plugin

### PR DESCRIPTION
**Pull request by sla89**
see PR https://github.com/volumio/volumio-plugins/pull/80 and https://github.com/volumio/volumio-plugins/pull/81 and https://github.com/volumio/volumio-plugins/pull/83 -> now increased version number in code

### CODE REVIEW

**Comment by volumio** [comment]
@sla89 Hi Stefan, nice addition! I took the freedom to add the new icon which will show in the next Volumio version... 
I also tried to publish on x86, however I saw that on x86 platform the plugin was not able to play aynithing, just telling failed to decode. Maybe the fact its faster somehows breaks the plugin.
Any idea about what it can be?

**Comment by sla89** [comment]
@volumio thank you. Do you have an error log for me? I dont think it has something to do with the faster platform.

**Comment by volumio** [comment]
@sla89 sure, there you have it:
http://logs.volumio.org/volumio/YxcHAj0.html

**Comment by sla89** [comment]
@volumio I cannot find the error in the log. Can you tell me how I can reproduce this? I dont know how to build for x86 and so on.

**Comment by sla89** [comment]
@volumio I have now a x86 volumio running in my virtual box and will take a look at it

**Comment by volumio** [comment]
Great! Let me know if you need any help!

**Pull request merged**
