### PR TITLE
Update to plugins

### PR DESCRIPTION
**Pull request by Saiyato**
I think the previous PR went wrong, is this one better?

### CODE REVIEW

**Comment by volumio** [comment]
Fixed, will test next week, thanks!

**Comment by Saiyato** [comment]
Just added a commit which removes the symlink to tvservice, had forgotten that one earlier.

**Comment by Saiyato** [comment]
Updated the LastFM plugin, it should now install properly from the UI using my forked version of simple-lastfm.

**Comment by volumio** [comment]
I'm super busy ATM, but thanks for the updated PR, I look forward to free myself up a bit and try it ...

**Comment by Saiyato** [comment]
Just added my new rotary encoder plugin to the PR

**Comment by Saiyato** [comment]
And the first bug fix for the rotary encoder is a fact.

**Pull request merged**
