### PR TITLE
optimized start parameters

### PR DESCRIPTION
**Pull request by escoand**

### CODE REVIEW

**Comment by volumio** [comment]
Interesting, however I will disable incognito, since it disables caching on reboots (albumarts will be downloaded every time). 
What are the advantages of the other parameters?
Is there a way to set on screen keyboard?

**Comment by escoand** [comment]
you are deleting the cache directory every restart - this is practical the same
this should be no problem because everything is only on localhost

**Comment by escoand** [comment]
http://peter.sh/experiments/chromium-command-line-switches
I tried all keyboard switches but non worked for me

**Comment by volumio** [comment]
Actually, downloading albumarts (even if they are on localhost) adds a little overhead. So, if possible I would remove the incogniito options... Or if there's a specific reason or advantage tell me and we'll keep it

**Comment by escoand** [comment]
--disable-3d-apis \\ hoped this will speed up the startup a bit
--disable-breakpad \\ deactivate the crash reporter
--disable-crash-reporter \\ deactivate the crash reporter
--disable-translate \\ i was asked i want to translate the english ui

**Comment by volumio** [comment]
I agree with the above! Can you remove incognito? Then I merge!

**Comment by escoand** [comment]
did not try the double backslash thing but this should work ;-)

**Comment by escoand** [comment]
https://chrome.google.com/webstore/detail/virtual-keyboard/pflmllfnnabikmfkkaddkoolinlfninn

**Comment by volumio** [comment]
Interesting, but how do we install it from script?

**Comment by escoand** [comment]
It seems we need the crx file:
http://chrome-extension-downloader.com/2f941946f042a34d6ac674c90055165f/pflmllfnnabikmfkkaddkoolinlfninn/Virtual-Keyboard_v1.11.1.crx

**Pull request merged**
