### PR TITLE
touch_display: Allow four rotations

### PR DESCRIPTION
**Pull request by colinleroy**
Hi folks,

I've modified the touch_display plugin to be able to use it on any screen and in any orientation.
The new code relies on a tool I developed independantly (https://github.com/colinleroy/raspi-rotate), which uses Xorg configuration instead of kernel parameters.

**Advantages**:
- it works with any screen, not just rPi screens
- it works in any orientation, normal, 90° clockwise, upside-down and 90° counter-clockwise
- changing the orientation doesn't need a reboot but only a restart of volumio-kiosk.service

**Inconvenient**:
- it may be a little bit slower than using lcd_rotate. I could only test it on a Raspberry pi 3, on which no performance drop is noticeable.

**Caveat**:
- the install script generates rotated bootsplash pngs, which require installing (then removing) imagemagick, and makes the plugin first install a bit longer.

I hope you'll like it, and look forward to reading your thoughts on it.

### CODE REVIEW

**Comment by balbuze** [comment]
nice! I will test asap!

**Comment by gvolt** [comment]
IMHO we should consider to realize the rotation function without adding further depencies (imagemagick and raspi-rotate). The manipulation of /etc/X11/xorg.conf.d/40-libinput.conf in order to adjust the touch orientation accordingly to the display rotation could be done by the plugin itself (i.e. without the need to pull scripts from an external resource).

Rotation itself should be doable utilizing display_lcd_rotate and display_hdmi_rotate in /boot/config.txt. I recently tested display_lcd_rotate on a Pi 3B and my previous [assumption](https://github.com/volumio/volumio-plugins/pull/348#issuecomment-522364441) that this would require more RAM allocated for the GPU has been proven wrong (at least for the recent value of gpu_mem=32MB). Using this method requires a reboot after settings have been changed by the user, but has the advantage that the bootsplash image gets rotated automtically so imagemagick would not be necessary. Furthermore imagemagick is installed and run only during the installation of the plugin, so plymouth themes added later on would not get any rotated images unless the plugin gets reinstalled.

What are your opinions?

**Comment by balbuze** [comment]
I revert it, waiting for more informations. But it is a missing feature that would be nice to be added.

**Comment by colinleroy** [comment]
I can try implementing gvolt's idea ! Will keep you informed :)

**Comment by volumio** [comment]
I second gvolt's remark:
- We want to use display_lcd_rotate and display_hdmi_rotate in config.txt, rather than xorg configurations (rotation in xorg is very inefficient).
- Let's not install imagemagik and then uninstall, better to provide already rotated images.

**Comment by colinleroy** [comment]
Hi,
I've reworked that in #358 :)

**Pull request merged**
