### PR TITLE
Protect OnVolumioStart

### PR DESCRIPTION
**Pull request by petecallaghan**
Created in response to https://github.com/volumio/Volumio2-UI/issues/801

### CODE REVIEW

**Comment by volumio** [comment]
Is there a reason why the functions

self.writeAllConfigParameters();

self.executeScriptAsSudo(buildShieldScript);

are still called on the onVolumioStart? 

This should not be like that, as you want to carry out all the functionalities of the plugin from the onStart function. This way, the plugins applies his effects only when started.
If there is no particular reason, please have them running only on onStart

**Comment by petecallaghan** [comment]
I have tested removing those lines from onVolumioStart and the plugin still functions correctly. 

Thanks for your assistance.

**Comment by balbuze** [comment]
is it ready for you?

**Comment by petecallaghan** [comment]
Hi, yes @balbuze it is ready to be merged. Thanks

**Comment by balbuze** [comment]
show status returns nothing on RPI.

**Pull request merged**
