### PR TITLE
updating plugin audiophile_audition 1.0.0

### PR DESCRIPTION
**Pull request by pattdepanick**
Reactivating previous request #370 
Please merge this new plugin for the greek network stream https://stream.psychomed.gr/index.html

Source is now available as well as zip file for tests

### CODE REVIEW

**Comment by balbuze** [comment]
hello! well done but : 
- the plugin cannot be uninstalled
- do not provide zip (it is generated while publishing the plugin)
I let you check! TY

**Comment by pattdepanick** [comment]
Thanks Balbuze.

I did not know about the radios . There are indeed  from the same source.

I created the plugin without knowing their existences I must admit.

Concerning the uninstqll issue : When I click on uninstall button in plugin pages : the plug gets uninstalled : the successful message appears and the /data/plugins/music_service/ folder does not show anymore the audiophile_audition folder.

I am running  volumio 2.791

I will remove the zip; I did not know where to host it to qllow manual install while waiting for the plugin to be added to the official plugin list (which may not occur if present in the regular  web radio list).

I created the plugin as a training to better understand how this was working.

**Comment by balbuze** [comment]
hello! No problem!
In fact, if you want to create a plugin with the zip, just publish it on our github and give the link.
But when you want it to be an official plugin, remove node_modules and zip. They are auto generated while testing the plugin.
You'll understand we can't add a plugin with strictly same features than standard. Next time ;-) ! Thanks again for your work!

**Comment by balbuze** [comment]
sorry, I close it

**Pull request closed without merging**
