### PR TITLE
volspotconnect2 - cleanup startconnect.sh

### PR DESCRIPTION
**Pull request by balbuze**
I made several test and it works on my systems...
I just removed some lines in startconnect.sh to clean it, but I don't see why it don't work in your case.
let me know ;-)

### CODE REVIEW

**Comment by volumio** [comment]
@balbuze also I tried for x86, but does not work:
Feb 18 17:05:38 volumiox volumio[15059]: INFO:librespot: librespot d9deef8 (2018-02-06). Built on 2018-02-07. Build ID: XU6RsV8b
Feb 18 17:05:38 volumiox volumio[14749]: info: Volspotconnect Daemon Started
Feb 18 17:05:38 volumiox volumio[14749]: info: [SpConDebug] Volspotconnect Started
Feb 18 17:05:38 volumiox volumio[14749]: info: [SpConDebug] Starting metadata listener
Feb 18 17:05:38 volumiox volumio[14749]: { Error: bind EADDRINUSE 0.0.0.0:5000
Feb 18 17:05:38 volumiox volumio[14749]: at Object.exports._errnoException (util.js:1018:11)
Feb 18 17:05:38 volumiox volumio[14749]: at exports._exceptionWithHostPort (util.js:1041:20)
Feb 18 17:05:38 volumiox volumio[14749]: at _handle.lookup (dgram.js:219:18)
Feb 18 17:05:38 volumiox volumio[14749]: at _combinedTickCallback (internal/process/next_tick.js:83:11)
Feb 18 17:05:38 volumiox volumio[14749]: at process._tickCallback (internal/process/next_tick.js:104:9)
Feb 18 17:05:38 volumiox volumio[14749]: code: 'EADDRINUSE',
Feb 18 17:05:38 volumiox volumio[14749]: errno: 'EADDRINUSE',
Feb 18 17:05:38 volumiox volumio[14749]: syscall: 'bind',
Feb 18 17:05:38 volumiox volumio[14749]: address: '0.0.0.0',
Feb 18 17:05:38 volumiox volumio[14749]: port: 5000 }
Feb 18 17:05:38 volumiox volumio[14749]: info: Done.
Feb 18 17:05:38 volumiox volumio[15059]: WARN:mdns: Failed to register IPv6 receiver: Error { repr: Os { code: 19, message: "No such device" } }


Could you give it a look? Maybe you can ask gé for an help to see if ipv6 is related..

**Comment by balbuze** [comment]
Humm, IPv6 error is not a problem, we can forget it.
For the EADDRINUSE, it is often due to a restart of node (after a killall node). But it should not be a problem.I'm using it in virtual machine x86 and it works. I even remove it and re-install.
let me know if still problematic.

**Comment by volumio** [comment]
Then the plugin should understand the error and retry after a few seconds, this is the only way we can make it work.
Also, port 5000 is used by shairport-sync, this might be the issue . Can the port be changed?

**Comment by balbuze** [comment]
Ok. I understand now. I was searching what used port 5000. I thought it was librespot that not release this.. I going to change it and recompile librespot.

**Pull request merged**
