### PR TITLE
Radio Paradise plugin: Reflecting recent changes in FLAC streams

### PR DESCRIPTION
**Pull request by lwi-p**
RP added metadata to the FLAC streams which seems to produce stability and audio issues. RP provides also FLAC without metadata. When links are modified to use those streams without metadata, sound and stability improved. We do not need in-stream metadata, as we collect them from API calls.
RP also renamed Eclectic mix to World/Etc, so this is to reflect this as well.

### CODE REVIEW

**Comment by lwi-p** [comment]
RP just again changed their links for FLAC streams without metadata. Links look almost the same as they were before last change. The difference is that they use https and link for Eclectic mix changed to World/Etc. So reflecting this.

**Comment by jean-m-cyr** [comment]
Any intentions of merging this PR? I could patch it locally, but then software updates would fail.

**Comment by lwi-p** [comment]
Is it waiting for any action from my side? Or just for commit from someone with write access?

**Comment by balbuze** [comment]
sorry for the delay ;-) done!

**Comment by jean-m-cyr** [comment]
Thanks

**Pull request merged**
