### PR TITLE
Nanosoundcd v1.1.4

### PR DESCRIPTION
**Pull request by nanomesher**
Added x86 support

### CODE REVIEW

**Comment by balbuze** [comment]
Hi!
Some issue when enabling the plugin (Rpi4):
Sep 21 08:42:23 volumio-rpi4 volumio[840]: info: Enabling plugin nanosound
Sep 21 08:42:23 volumio-rpi4 volumio[840]: info: Loading plugin "nanosound"...
Sep 21 08:42:23 volumio-rpi4 volumio[840]: error: !!!! WARNING !!!!
Sep 21 08:42:23 volumio-rpi4 volumio[840]: error: The plugin miscellanea/nanosound failed to load, setting it to stopped. Error: Error: Cannot find module 'onoff'
Sep 21 08:42:23 volumio-rpi4 volumio[840]: error: Stack trace: Error: Cannot find module 'onoff'
Can you have a look please?

**Comment by nanomesher** [comment]
Is it all good now?

**Comment by balbuze** [comment]
It is now ok for arm. But for x86 (on a VM) the plugin hangs volumio. It seems related to the VM but I can't check. 
Sep 21 15:59:18 volumio-x86 volumio[2748]: info: NanoSound - Creating button triggers
Sep 21 15:59:18 volumio-x86 volumio[2748]: info: NanoSound - Creating button triggers for DAC
Sep 21 15:59:18 volumio-x86 volumio[2748]: info: playPause on pin 13
Sep 21 15:59:18 volumio-x86 volumio[2748]: fs.js:646
Sep 21 15:59:18 volumio-x86 volumio[2748]: return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
Sep 21 15:59:18 volumio-x86 volumio[2748]: ^
Sep 21 15:59:18 volumio-x86 volumio[2748]: Error: ENOENT: no such file or directory, open '/sys/class/gpio/export'
Sep 21 15:59:18 volumio-x86 volumio[2748]: at Object.fs.openSync (fs.js:646:18)
Sep 21 15:59:18 volumio-x86 volumio[2748]: at Object.fs.writeFileSync (fs.js:1299:33)
Sep 21 15:59:18 volumio-x86 volumio[2748]: at new Gpio (/data/plugins/miscellanea/nanosound/node_modules/onoff/onoff.js:82:8)
Sep 21 15:59:18 volumio-x86 volumio[2748]: at /data/plugins/miscellanea/nanosound/index.js:216:11
Sep 21 15:59:18 volumio-x86 volumio[2748]: at Array.forEach (<anonymous>)
Sep 21 15:59:18 volumio-x86 volumio[2748]: at nanosound.createTriggers (/data/plugins/miscellanea/nanosound/index.js:211:10)
Sep 21 15:59:18 volumio-x86 volumio[2748]: at nanosound.onStart (/data/plugins/miscellanea/nanosound/index.js:129:7)
Sep 21 15:59:18 volumio-x86 volumio[2748]: at PluginManager.startCorePlugin (/volumio/app/pluginmanager.js:299:30)
Is it ok with your test?

**Comment by balbuze** [comment]
I realise something : why your title is Nanosoundcd v1.1.4? 
The plugin is "version": "1.8.0",
	"description": "Companion plugin for NanoSound DAC",

**Comment by nanomesher** [comment]
To clear the confusion, there are 2 plugins we own and have PR for:
1) nanosound plugin under plugins/miscellanea/nanosound . The current version is v1.8.0. The PR is #354. This plugin only works for Raspberry Pi, so you dont need to test with x86.
2) nanosound_cd plugin under plugins/music_service/nanosound_cd.  The latest version is v1.1.4.  The PR is #355.  This plugin works on arm and x86.

Sorry about the confusion

**Comment by balbuze** [comment]
Ok. So nanosound 1.8.0 is ok and published. I'll have a look for the other

**Comment by nanomesher** [comment]
nanosound 1.8.0 needs to be remerged and republished
nanosound_cd 1.1.4 needs to be published

thanks a lot

**Comment by balbuze** [comment]
cd 1.1.4 published for x86 and arm

**Pull request merged**
