### PR TITLE
provide new plugin : status2mqtt 1.0.0

### PR DESCRIPTION
**Pull request by jit06**
This plugin allow volumio to plublish status (play, stop, pause) to an  mqtt server

### CODE REVIEW

**Comment by jit06** [comment]
Added another plugin that blink led wired to a gpio pin if current status is playing

**Comment by balbuze** [comment]
Please, send a PR in master branch with only source code, no node modules, no zip. We take care of this when testing/publishing

**Comment by jit06** [comment]
sorry, I just followed the tutorial on volumio's webpage about developpers and plugin, but it seems that is messed out all my fork

**Comment by fherbet** [comment]
Hi @jit06 , i can't get this plugin to work...

i've got a proper mqtt server installed on my jeedom and can publish topic from various clients...
i just filled the plugin settings with same parameters , but it looks like no volumio status is published to my mqtt server...

how can i troubleshoot this ? thanks !

**Comment by jit06** [comment]
Hi @fherbet , I just tested on mine and I found the status published on my mqtt server. Through I hae to admit that I'm not using a user nor a password... is it your case ?

Also, did you put the prefix "mqtt://" in the hostname ?

**Pull request closed without merging**
