### PR TITLE
Volusonic

### PR DESCRIPTION
**Pull request by foobarjo**
due to some mistake I had to delete the previous pull request

### CODE REVIEW

**Comment by Ghembs** [comment]
Hi there,

I reviewed your plugin and have a few feedback for you:
 - disabling the plugin, the password has to be reset
 - goto album doesn't work properly (but this is a known issue)
 - research is good but there are no icons in the artists section

Since these aren't major issues I'm going to merge, I'll check right now if I can solve something.

nice music library by the way!

**Comment by foobarjo** [comment]
Hi Giuliano, 

Thanks for testing. 

- Reset password: done 

- icon in search & artists: done 

About the goto function, i wrote a goto function to replace the one in
app/musiclibrary.js  

CoreMusicLibrary.prototype.goto=function(data){
        var self = this;
        var defer=libQ.defer();

        //we get track from the queue since it contains plugin's private
datas
        var track =
self.commandRouter.stateMachine.playQueue.getTrack(self.commandRouter.stateMachine.currentPosition);

        if (track.service != 'mpd') {
                data.track = track;
               
defer.resolve(self.commandRouter.executeOnPlugin('music_service',track.service,'goto',data));
        }else{
               
defer.resolve(self.commandRouter.executeOnPlugin('music_service','mpd','goto',data));
        }
        return defer.promise;
} 

It works with this one. We were talking about that with Michelangelo. I
can probably get the track on the plugin side but in anyway we have to
defer the call don't we? 

What do you think? 

I'll PR a v0.0.8 with all corrections once we will be sure of where we'r
going with the goto function. 

jo 

Le 12.03.2019 12:00, Giuliano Gambacorta a écrit :

> Hi there, 
> 
> I reviewed your plugin and have a few feedback for you: 
> 
> * disabling the plugin, the password has to be reset
> * goto album doesn't work properly (but this is a known issue)
> * research is good but there are no icons in the artists section
> 
> Since these aren't major issues I'm going to merge, I'll check right now if I can solve something. 
> 
> nice music library by the way! 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/volumio/volumio-plugins/pull/306#issuecomment-472089748
[2]

**Comment by foobarjo** [comment]
I got the goto function work without touching app/musiclibrary so i made
a new PR with the changes 

Le 12.03.2019 12:00, Giuliano Gambacorta a écrit :

> Hi there, 
> 
> I reviewed your plugin and have a few feedback for you: 
> 
> * disabling the plugin, the password has to be reset
> * goto album doesn't work properly (but this is a known issue)
> * research is good but there are no icons in the artists section
> 
> Since these aren't major issues I'm going to merge, I'll check right now if I can solve something. 
> 
> nice music library by the way! 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/volumio/volumio-plugins/pull/306#issuecomment-472089748
[2]

**Comment by foobarjo** [comment]
Hi Giuliano, 

I guess the last PR is the final one. 

I did correct the issues you noted and made some last details
corrections to the code. 

Thanks again. 

Jo 

Le 12.03.2019 12:00, Giuliano Gambacorta a écrit :

> Hi there, 
> 
> I reviewed your plugin and have a few feedback for you: 
> 
> * disabling the plugin, the password has to be reset
> * goto album doesn't work properly (but this is a known issue)
> * research is good but there are no icons in the artists section
> 
> Since these aren't major issues I'm going to merge, I'll check right now if I can solve something. 
> 
> nice music library by the way! 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/volumio/volumio-plugins/pull/306#issuecomment-472089748
[2]

**Pull request merged**
